# Eureka Zone for Docker Network
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/

# Zipkin Endpoint for Docker Network
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# RabbitMQ Host for Docker Network
spring.rabbitmq.host=rabbitmq
