spring.application.name=gateway-service
server.port=8080

# Load configurations from Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Actuator
management.endpoints.web.exposure.include=*

# Gateway Filters
spring.cloud.gateway.default-filters[0]=JwtAuthenticationFilter
