spring.application.name=discovery-service
# Server Configuration
server.port=8761
# Eureka Configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
eureka.instance.hostname=localhost
